service:
  name: cognito

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:env, 'preint'}
  region: ${file(./config/config.yml):${self:provider.stage}.aws.REGION, 'us-west-2'}


functions:
  defineAuthChallenge:
    handler: src/lambda/DefineAuthChallenge/index.handler
  createAuthChallenge:
    handler: src/lambda/CreateAuthChallenge/index.handler
    iamRoleStatements:
      - Effect: "Allow"
        Action: "ses:SendEmail"
        Resource: "*"
  verifyAuthChallenge:
    handler: src/lambda/VerifyAuthChallenge/index.handler
